---
- name: "Install MariaDB"
  yum:
    name: ['mariadb-server', 'MySQL-python']
    state: present
  when: ansible_os_family == "RedHat"

- name: Configure SELinux to start mysql on any port
  seboolean:
    name: mysql_connect_any
    state: true
    persistent: yes

- name: "Install .my.cnf with credentials"
  template:
    src: templates/my.cnf.j2
    dest: /etc/my.cnf
    mode: 0400
    owner: root
    group: root
  notify: "restart ${{ mysqlservice }}"
  tags: my_cnf

- name: "Create MariaDB log file"
  file:
    path: /var/log/mysqld.log
    state: touch
    owner: mysql
    group: mysql
    mode: 0775

- name: "Create MariaDB PID directory"
  file:
    path: /var/run/mysqld
    state: directory
    owner: mysql
    group: mysql
    mode: 0775

- name: "Start & Enable MariaDB Server to start on boot"
  service:
    name: "{{ mysqlservice }}"
    state: started
    enabled: yes

- name: "Deletes anonymous MySQL server user for localhost"
  mysql_user:
    user: ""
    state: "absent"
    login_user: root
    login_password: "{{ mysql_root_pass }}"

- name: "Secures MariaDB root user"
  mysql_user:
    user: "root"
    password: "{{ mysql_root_pass }}"
    host: "{{ item }}"
    login_password: "{{mysql_root_pass}}"
    login_user: root
  with_items:
    - 127.0.0.1
    - localhost
    - ::1
    - "{{ ansible_fqdn }}"

- name: "Removes the MySQL test database"
  mysql_db:
    db: test
    state: absent
    login_password: "{{ mysql_root_pass }}"


# -  set_fact:
#     mysql_root_pw: "{{ mysql_root_pass }}"


- name: "Start firewalld"
  service:
    name: firewalld
    state: started
    enabled: yes

- name: "Enable MySQL firewall port"
  firewalld:
    port: "${{ mysql_port }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  notify: restart firewalld

- name: "Create the database for website"
  mysql_db:
    name: "{{ dbname }}"
    state: present

- name: "Create the Application user for the database"
  mysql_user:
    name: "{{ dbuser }}"
    password: "{{ upassword }}"
    priv: '${{ dbname }}.*:ALL'
    host: '%'
    state: present