---
all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
prod:
  hosts:
    srv1:
      ansible_host: srv1 #10.0.0.4
      ansible_user: adminsrv1
      ansible_ssh_pass: "{{ srv1_ssh_pass }}"
    srv2:
      ansible_host: srv2 #10.0.0.5
      ansible_user: adminsrv2
      ansible_ssh_pass: "{{ srv2_ssh_pass }}"