---
- name: "DOCKER CE INSTALLATION ON DEBIAN|UBUNTU"
  hosts: all
  become: true

  pre_tasks:
    - name: "Installing Prerequisite packages"
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'lsb-release', 'gnupg']
        state: present
        update_cache: true

    - name: "Adding repository signing key"
      apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: "Adding docker repository into sources list"
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: "Installing Docker-CE and dependencies"
      package:
        name: ['docker-ce', 'docker.io', 'docker-compose', 'docker-registry']
        state: present
        update_cache: true

    - name: "Starting and Enabling Docker service"
      service:
        name: docker
        state: started
        enabled: yes

    - name: "Adding admin user to docker group"
      user:
        name: admin
        groups: docker
        append: yes