---
- name: "DOCKER CE INSTALLATION ON CENTOS"
  hosts: prod
  become: true

  pre_tasks:
    - name: "Installing Docker Prerequisite packages"
      yum:
        name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2']
        state: present

    - name: "Configuring docker-ce repo"
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    # - name: "Enabling docker-ce-edge and docker-ce-test repos"
    #   ini_file:
    #     path: /etc/yum.repos.d/docer-ce.repo
    #     section: {{ item }}
    #     option: enabled
    #     value: "0"
    #   with_items:
    #     - docker-ce-edge
    #     - docker-ce-test

    - name: "Installing Docker-CE"
      package:
        name: docker-ce
        state: present

    - name: "Adding admin user to docker group"
      user:
        name: admin
        groups: docker
        append: yes

    - name: "Starting and Enabling Docker service"
      service:
        name: docker
        state: started
        enabled: yes